sudo: required
services:
  - docker

before_install:
  - docker build -t fuat/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true fuat/react-test npm test

after_success:
  - docker build -t fuat/multi-client ./client
  - docker build -t fuat/multi-nginx ./nginx
  - docker build -t fuat/multi-server ./server
  - docker build -t fuat/multi-worker ./worker 
  
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  # Take those images and push the to docker hub
  - docker push fuat/multi-client
  - docker push fuat/multi-nginx
  - docker push fuat/multi-server
  - docker push fuat/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-254289330288
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY